language: python
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

python:
  - "2.7"

services:
  - mysql

install:
  - pip install flake8==3.3.0
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - sudo rm /etc/apt/sources.list.d/docker.list
  - sudo apt-get purge -y mysql-common mysql-server mysql-client
  - nvm install v7.10.0
  - wget https://raw.githubusercontent.com/vmraid/chair/master/playbooks/install.py
  - sudo python install.py --develop --user travis --without-chair-setup
  - sudo pip install -e ~/chair

  - rm $TRAVIS_BUILD_DIR/.git/shallow
  - bash $TRAVIS_BUILD_DIR/travis/chair_init.sh
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/vmraid-chair/sites/

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - mysql -u root -ptravis -e 'create database test_vmraid'
  - echo "USE mysql;\nCREATE USER 'test_vmraid'@'localhost' IDENTIFIED BY 'test_vmraid';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_vmraid\`.* TO 'test_vmraid'@'localhost';\n" | mysql -u root -ptravis

  - cd ~/vmraid-chair
  - chair get-app chair_manager $TRAVIS_BUILD_DIR
  - chair reinstall --yes
  - chair build
  - chair scheduler disable
  - chair start &
  - sleep 10

script:
  - set -e
  - chair --site sitename run-tests #todo
  - sleep 5
  - chair reinstall --yes
  - chair execute erpadda.setup.setup_wizard.utils.complete
  - chair execute erpadda.setup.utils.enable_all_roles_and_domains
  - chair --site sitename run-ui-tests --app chair_manager